### ISSUE TITLE
TypeError: Cannot read property 'true' of undefined

### ISSUE THREAD

**Issue by duckworth** [Kikobeats/meaning-cloud#1]
I believe    credentials.url = DEFAULT.SECURE_MODES[secure] should be singular SECURE_MODE

getting the following error:

```
$ node
> var MeaningCloud = require('meaning-cloud');
undefined
> var meaning = MeaningCloud({
...   key: 'xxxxx'
...   });
TypeError: Cannot read property 'true' of undefined
  at module.exports (/Users/duckworth/Repos/hsdnapi/node_modules/meaning-cloud/lib/Meaning.Credentials.coffee:19:42)
  at module.exports (/Users/duckworth/Repos/hsdnapi/node_modules/meaning-cloud/lib/Meaning.coffee:30:19)
  at repl:1:15
  at REPLServer.defaultEval (repl.js:248:27)
  at bound (domain.js:280:14)
  at REPLServer.runBound [as eval] (domain.js:293:12)
  at REPLServer.<anonymous> (repl.js:412:12)
  at emitOne (events.js:82:20)
  at REPLServer.emit (events.js:169:7)
  at REPLServer.Interface._onLine (readline.js:210:10)
  at REPLServer.Interface._line (readline.js:549:8)
  at REPLServer.Interface._ttyWrite (readline.js:826:14)
  at ReadStream.onkeypress (readline.js:105:10)
  at emitTwo (events.js:87:13)
  at ReadStream.emit (events.js:172:7)
  at emitKeys (readline.js:1250:14)
  at [object Generator].next (native)
  at ReadStream.onData (readline.js:918:36)
  at emitOne (events.js:77:13)
  at ReadStream.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at ReadStream.Readable.push (_stream_readable.js:110:10)
  at TTY.onread (net.js:523:20)
```

**Comment by Kikobeats** [comment]
Fixed, thanks!
